name: Pipeline CI/CD Simulation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js pour les tests
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Vérifier Node.js
        run: node --version
      - name: Exécuter les tests
        run: node test.js
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_dir: ./

          - name: Build and Push Docker Image
  uses: docker/build-push-action@v5
  with:
    push: true
    tags: yourdockerhubusername/pipeline-app:${{ github.sha }}